script: bash build_helpers/buildDistFromTravis.sh
env:
  global:
  - GH_REF: github.com/kimagure/fixed-data-table
  - secure: FsuavrWIOWipuK7pZf57BVQeSdQijbxFBjubnCodVgpfpRcuC85D3jCxQFKG/auCaC28F1rgUzYBO+cPttza0SBu9fy9xLFAAikWkm8klrQsUqgFUi8bLMCWXbsaqH0iRCcjQ6xDKVN+U4lnHVJOqgYqfh4BOJ5q8dOwGmPJe1U=
language: node_js
node_js:
- '0.10'
